# Generated by Django 5.2.4 on 2025-07-31 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('security', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login_failed', 'Login Failed'), ('access_denied', 'Access Denied'), ('breach_attempt', 'Breach Attempt'), ('data_access', 'Data Access'), ('data_modification', 'Data Modification'), ('data_export', 'Data Export'), ('user_creation', 'User Creation'), ('user_modification', 'User Modification'), ('permission_change', 'Permission Change'), ('system_error', 'System Error'), ('security_alert', 'Security Alert')], help_text='Type of security event', max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Severity level of the event', max_length=20)),
                ('description', models.TextField(help_text='Description of the security event')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string')),
                ('request_path', models.CharField(blank=True, help_text='Request path/URL', max_length=500)),
                ('request_method', models.CharField(blank=True, help_text='HTTP method used', max_length=10)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the event')),
                ('is_resolved', models.BooleanField(default=False, help_text='Whether the security event has been resolved')),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes about how the event was resolved')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the security event was resolved', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the security event occurred')),
            ],
            options={
                'verbose_name': 'Security Event',
                'verbose_name_plural': 'Security Events',
                'db_table': 'security_events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RenameIndex(
            model_name='anonymizeddataset',
            new_name='security_an_dataset_d284bd_idx',
            old_name='anonymized_datasets_type_status_idx',
        ),
        migrations.RenameIndex(
            model_name='anonymizeddataset',
            new_name='security_an_created_4e4da3_idx',
            old_name='anonymized_datasets_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='anonymizeddataset',
            new_name='security_an_expires_b20b5a_idx',
            old_name='anonymized_datasets_expires_at_idx',
        ),
        migrations.RenameIndex(
            model_name='anonymizeddataset',
            new_name='security_an_created_1fcdaa_idx',
            old_name='anonymized_datasets_created_by_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_user_id_d685f3_idx',
            old_name='audit_logs_user_action_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_content_b0ef47_idx',
            old_name='audit_logs_content_type_object_id_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_action_474804_idx',
            old_name='audit_logs_action_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_severit_549d29_idx',
            old_name='audit_logs_severity_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_ip_addr_932507_idx',
            old_name='audit_logs_ip_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_timesta_423be6_idx',
            old_name='audit_logs_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='datasetaccesslog',
            new_name='security_da_dataset_20b71a_idx',
            old_name='dataset_access_logs_dataset_user_idx',
        ),
        migrations.RenameIndex(
            model_name='datasetaccesslog',
            new_name='security_da_access__af04d8_idx',
            old_name='dataset_access_logs_access_type_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='datasetaccesslog',
            new_name='security_da_timesta_e84ea2_idx',
            old_name='dataset_access_logs_timestamp_idx',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='Content type of the object', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID of the object', null=True),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='resolved_by',
            field=models.ForeignKey(blank=True, help_text='User who resolved the security event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_security_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User associated with the security event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['event_type', 'timestamp'], name='security_ev_event_t_efa0a0_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['severity', 'timestamp'], name='security_ev_severit_db68de_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['user', 'timestamp'], name='security_ev_user_id_6a5f21_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['ip_address', 'timestamp'], name='security_ev_ip_addr_038026_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['is_resolved', 'timestamp'], name='security_ev_is_reso_689f48_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['timestamp'], name='security_ev_timesta_96e9ee_idx'),
        ),
    ]
