# Generated by Django 5.2.4 on 2025-07-31 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_securityevent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='content_type',
            field=models.ForeignKey(
                blank=True,
                help_text='Content type of the object',
                null=True,
                on_delete=models.deletion.CASCADE,
                to='contenttypes.contenttype'
            ),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_id',
            field=models.PositiveIntegerField(
                blank=True,
                help_text='ID of the object',
                null=True
            ),
        ),
    ]
