# Generated by Django 5.2.4 on 2025-07-31 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_auto_20250731_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('read', 'Read'), ('update', 'Update'), ('delete', 'Delete'), ('export', 'Export'), ('import', 'Import'), ('login', 'Login'), ('login_success', 'Login Success'), ('login_failure', 'Login Failure'), ('logout', 'Logout'), ('access_denied', 'Access Denied'), ('password_change', 'Password Change'), ('permission_change', 'Permission Change'), ('data_anonymization', 'Data Anonymization'), ('breach_attempt', 'Breach Attempt'), ('security_event', 'Security Event')], help_text='Type of action performed', max_length=50),
        ),
    ]
