# Generated by Django 5.2.4 on 2025-07-31 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='session_id',
            field=models.CharField(blank=True, help_text='Session ID', max_length=100, null=True),
        ),
    ]
