# Generated by Django 5.2.4 on 2025-08-06 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_alter_auditlog_session_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='securityevent',
            options={'ordering': ['-timestamp'], 'permissions': [('view_security_events', 'Can view security events'), ('manage_security_events', 'Can manage security events'), ('export_security_events', 'Can export security events'), ('resolve_security_events', 'Can resolve security events')], 'verbose_name': 'Security Event', 'verbose_name_plural': 'Security Events'},
        ),
    ]
