# Generated by Django 5.2.4 on 2025-08-06 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0006_alter_securityevent_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthcareRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the healthcare role', max_length=100, unique=True)),
                ('role_type', models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('pharmacist', 'Pharmacist'), ('pharmacy_tech', 'Pharmacy Technician'), ('administrator', 'Administrator'), ('receptionist', 'Receptionist'), ('billing_specialist', 'Billing Specialist'), ('it_admin', 'IT Administrator'), ('system_admin', 'System Administrator'), ('researcher', 'Researcher'), ('data_analyst', 'Data Analyst'), ('patient', 'Patient'), ('caregiver', 'Caregiver')], help_text='Type of healthcare role', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description of the role and its responsibilities')),
                ('access_level', models.CharField(choices=[('none', 'No Access'), ('own_data', 'Own Data Only'), ('assigned_patients', 'Assigned Patients'), ('department', 'Department Level'), ('organization', 'Organization Level'), ('system', 'System Level')], default='none', help_text='Maximum data access level for this role', max_length=30)),
                ('can_view_patient_data', models.BooleanField(default=False, help_text='Can view patient medical data')),
                ('can_edit_patient_data', models.BooleanField(default=False, help_text='Can edit patient medical data')),
                ('can_prescribe_medications', models.BooleanField(default=False, help_text='Can prescribe medications')),
                ('can_dispense_medications', models.BooleanField(default=False, help_text='Can dispense medications')),
                ('can_approve_prescriptions', models.BooleanField(default=False, help_text='Can approve prescriptions')),
                ('can_access_audit_logs', models.BooleanField(default=False, help_text='Can access audit logs')),
                ('can_export_data', models.BooleanField(default=False, help_text='Can export patient data')),
                ('can_manage_users', models.BooleanField(default=False, help_text='Can manage user accounts')),
                ('can_manage_roles', models.BooleanField(default=False, help_text='Can manage healthcare roles')),
            ],
            options={
                'verbose_name': 'Healthcare Role',
                'verbose_name_plural': 'Healthcare Roles',
                'db_table': 'healthcare_roles',
                'ordering': ['name'],
                'permissions': [('assign_healthcare_role', 'Can assign healthcare roles'), ('view_healthcare_role_permissions', 'Can view healthcare role permissions'), ('audit_healthcare_roles', 'Can audit healthcare role assignments')],
            },
        ),
        migrations.CreateModel(
            name='UserHealthcareRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='When the role was assigned')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the role assignment expires', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the role assignment is active')),
                ('requires_annual_review', models.BooleanField(default=True, help_text='Whether this role requires annual review')),
                ('last_reviewed_at', models.DateTimeField(blank=True, help_text='When the role was last reviewed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the role assignment')),
                ('assigned_by', models.ForeignKey(blank=True, help_text='User who assigned this role', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='User who conducted the last review', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_reviews_conducted', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(help_text='Healthcare role assigned to the user', on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='security.healthcarerole')),
                ('user', models.ForeignKey(help_text='User assigned to this role', on_delete=django.db.models.deletion.CASCADE, related_name='healthcare_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Healthcare Role',
                'verbose_name_plural': 'User Healthcare Roles',
                'db_table': 'user_healthcare_roles',
                'ordering': ['-assigned_at'],
                'permissions': [('review_role_assignments', 'Can review role assignments'), ('expire_role_assignments', 'Can expire role assignments')],
                'unique_together': {('user', 'role')},
            },
        ),
    ]
