# Generated by Django 5.2.4 on 2025-08-06 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0009_add_page_access_controls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, help_text='Django session key', max_length=40, unique=True)),
                ('state', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('expired', 'Expired'), ('terminated', 'Terminated'), ('under_review', 'Under Review')], default='active', help_text='Current state of the medical session', max_length=20)),
                ('access_level', models.CharField(choices=[('none', 'No Medical Data Access'), ('read_only', 'Read-Only Medical Data'), ('limited_write', 'Limited Write Access'), ('full_access', 'Full Medical Data Access'), ('emergency', 'Emergency Access')], default='none', help_text='Medical data access level for this session', max_length=20)),
                ('hipaa_consent_given', models.BooleanField(default=False, help_text='Whether HIPAA consent has been given for this session')),
                ('consent_timestamp', models.DateTimeField(blank=True, help_text='When HIPAA consent was given', null=True)),
                ('consent_ip_address', models.GenericIPAddressField(blank=True, help_text='IP address when consent was given', null=True)),
                ('device_fingerprint', models.TextField(blank=True, help_text='Device fingerprint for session validation')),
                ('location_data', models.JSONField(blank=True, default=dict, help_text='Geographic location data for session validation')),
                ('risk_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Security risk score for this session (0-100)', max_digits=5)),
                ('patient_records_accessed', models.JSONField(blank=True, default=list, help_text='List of patient records accessed in this session')),
                ('medical_actions_performed', models.JSONField(blank=True, default=list, help_text='List of medical actions performed in this session')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the session was created')),
                ('last_activity', models.DateTimeField(auto_now=True, help_text='Last activity timestamp')),
                ('expires_at', models.DateTimeField(help_text='When the session expires')),
                ('terminated_at', models.DateTimeField(blank=True, help_text='When the session was terminated', null=True)),
                ('termination_reason', models.TextField(blank=True, help_text='Reason for session termination')),
                ('terminated_by', models.ForeignKey(blank=True, help_text='User who terminated this session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminated_sessions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User associated with this session', on_delete=django.db.models.deletion.CASCADE, related_name='medical_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical Session',
                'verbose_name_plural': 'Medical Sessions',
                'db_table': 'medical_sessions',
                'ordering': ['-last_activity'],
                'permissions': [('view_medical_session', 'Can view medical session'), ('change_medical_session', 'Can change medical session'), ('delete_medical_session', 'Can delete medical session'), ('terminate_medical_session', 'Can terminate medical session'), ('audit_medical_session', 'Can audit medical session')],
                'indexes': [models.Index(fields=['session_key'], name='medical_ses_session_228ec9_idx'), models.Index(fields=['user', 'state'], name='medical_ses_user_id_7b9d42_idx'), models.Index(fields=['state', 'expires_at'], name='medical_ses_state_b5aa32_idx'), models.Index(fields=['access_level', 'state'], name='medical_ses_access__d4c54d_idx'), models.Index(fields=['last_activity'], name='medical_ses_last_ac_b3a8a2_idx'), models.Index(fields=['risk_score'], name='medical_ses_risk_sc_69f495_idx')],
            },
        ),
    ]
