# Generated by Django 5.2.4 on 2025-08-07 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0011_add_password_policies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptionKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.CharField(max_length=32, unique=True)),
                ('key_type', models.CharField(choices=[('fernet', 'Fernet'), ('rsa', 'RSA'), ('aes', 'AES')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Encryption Key',
                'verbose_name_plural': 'Encryption Keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(max_length=50)),
                ('form_data_hash', models.CharField(max_length=64)),
                ('encrypted_data', models.BinaryField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('validated', 'Validated'), ('processed', 'Processed'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('validation_errors', models.JSONField(default=list)),
                ('security_checks', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Form Submission Log',
                'verbose_name_plural': 'Form Submission Logs',
                'ordering': ['-submission_time'],
            },
        ),
        migrations.CreateModel(
            name='PatientDataLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('encrypt', 'Encrypt'), ('decrypt', 'Decrypt'), ('access', 'Access'), ('modify', 'Modify'), ('delete', 'Delete')], max_length=20)),
                ('data_type', models.CharField(max_length=20)),
                ('patient_id', models.IntegerField()),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('key_id', models.CharField(blank=True, max_length=32)),
                ('encryption_level', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('details', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_data_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient Data Log',
                'verbose_name_plural': 'Patient Data Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RateLimitViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('limit_type', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_limit_violations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rate Limit Violation',
                'verbose_name_plural': 'Rate Limit Violations',
                'ordering': ['-timestamp'],
            },
        ),
    ]
