# Generated by Django 5.2.4 on 2025-07-28 14:12

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(default='Welcome to MedGuard SA', help_text='Main title displayed in the hero section', max_length=200, verbose_name='Hero Title')),
                ('hero_subtitle', models.CharField(blank=True, help_text='Subtitle displayed below the hero title', max_length=500, verbose_name='Hero Subtitle')),
                ('hero_content', wagtail.fields.RichTextField(blank=True, help_text='Rich text content for the hero section', verbose_name='Hero Content')),
                ('main_content', wagtail.fields.RichTextField(blank=True, help_text='Main content area of the homepage', verbose_name='Main Content')),
                ('cta_title', models.CharField(blank=True, help_text='Title for the call to action section', max_length=200, verbose_name='Call to Action Title')),
                ('cta_content', wagtail.fields.RichTextField(blank=True, help_text='Content for the call to action section', verbose_name='Call to Action Content')),
                ('meta_description', models.CharField(blank=True, help_text='Description for search engines (max 160 characters)', max_length=160, verbose_name='Meta Description')),
            ],
            options={
                'verbose_name': 'Home Page',
                'verbose_name_plural': 'Home Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
