# Generated by Django 5.2.4 on 2025-07-28 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationlog',
            name='patient',
            field=models.ForeignKey(help_text='Patient who took the medication', on_delete=django.db.models.deletion.CASCADE, related_name='medication_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicationschedule',
            name='medication',
            field=models.ForeignKey(help_text='Medication to be taken', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='medications.medication'),
        ),
        migrations.AddField(
            model_name='medicationschedule',
            name='patient',
            field=models.ForeignKey(help_text='Patient for whom this schedule is created', on_delete=django.db.models.deletion.CASCADE, related_name='medication_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicationlog',
            name='schedule',
            field=models.ForeignKey(blank=True, help_text='Associated medication schedule', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='medications.medicationschedule'),
        ),
        migrations.AddField(
            model_name='stockalert',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, help_text='User who acknowledged the alert', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockalert',
            name='created_by',
            field=models.ForeignKey(help_text='User who created the alert', on_delete=django.db.models.deletion.CASCADE, related_name='created_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockalert',
            name='medication',
            field=models.ForeignKey(help_text='Medication associated with this alert', on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='medications.medication'),
        ),
        migrations.AddIndex(
            model_name='medicationschedule',
            index=models.Index(fields=['patient', 'medication'], name='medication__patient_643316_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationschedule',
            index=models.Index(fields=['timing'], name='medication__timing_9dd0ae_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationschedule',
            index=models.Index(fields=['status'], name='medication__status_6b2c27_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationschedule',
            index=models.Index(fields=['start_date', 'end_date'], name='medication__start_d_746dd0_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationlog',
            index=models.Index(fields=['patient', 'medication'], name='medication__patient_20e14f_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationlog',
            index=models.Index(fields=['scheduled_time'], name='medication__schedul_7185c1_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationlog',
            index=models.Index(fields=['status'], name='medication__status_600169_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationlog',
            index=models.Index(fields=['actual_time'], name='medication__actual__92ef2e_idx'),
        ),
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['medication'], name='stock_alert_medicat_591b31_idx'),
        ),
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['alert_type'], name='stock_alert_alert_t_206d4a_idx'),
        ),
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['priority'], name='stock_alert_priorit_5ad55f_idx'),
        ),
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['status'], name='stock_alert_status_2cc1a6_idx'),
        ),
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['created_at'], name='stock_alert_created_9f8b1b_idx'),
        ),
    ]
