# Generated by Django 5.2.4 on 2025-07-28 13:10

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Introduction text for the medications page', verbose_name='Introduction')),
            ],
            options={
                'verbose_name': 'Medication Index Page',
                'verbose_name_plural': 'Medication Index Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MedicationDetailPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('additional_info', wagtail.fields.RichTextField(blank=True, help_text='Additional information about the medication', verbose_name='Additional Information')),
                ('medication', models.OneToOneField(help_text='Associated medication record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detail_page', to='medications.medication', verbose_name='Medication')),
            ],
            options={
                'verbose_name': 'Medication Detail Page',
                'verbose_name_plural': 'Medication Detail Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
