# Generated by Django 5.2.4 on 2025-07-31 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0004_pharmacyintegration_prescriptionrenewal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationlog',
            name='patient',
            field=models.ForeignKey(help_text='Patient who took the medication', limit_choices_to={'user_type': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='medication_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicationschedule',
            name='patient',
            field=models.ForeignKey(help_text='Patient for whom this schedule is created', limit_choices_to={'user_type': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='medication_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prescriptionrenewal',
            name='patient',
            field=models.ForeignKey(help_text='Patient for this prescription', limit_choices_to={'user_type': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='prescription_renewals', to=settings.AUTH_USER_MODEL),
        ),
    ]
