# Generated by Django 5.2.4 on 2025-08-05 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0005_alter_medicationlog_patient_and_more'),
    ]

    operations = [
    ]
