# Generated by Django 5.2.4 on 2025-08-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0006_auto_20250805_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this medication was created'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this medication was last updated'),
        ),
        migrations.AlterField(
            model_name='medicationlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this medication log was created'),
        ),
        migrations.AlterField(
            model_name='medicationlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this medication log was last updated'),
        ),
        migrations.AlterField(
            model_name='medicationschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this medication schedule was created'),
        ),
        migrations.AlterField(
            model_name='medicationschedule',
            name='friday',
            field=models.BooleanField(default=True, help_text='Take medication on Friday'),
        ),
        migrations.AlterField(
            model_name='medicationschedule',
            name='monday',
            field=models.BooleanField(default=True, help_text='Take medication on Monday'),
        ),
        migrations.AlterField(
            model_name='medicationschedule',
            name='saturday',
            field=models.BooleanField(default=True, help_text='Take medication on Saturday'),
        ),
        migrations.AlterField(
            model_name='medicationschedule',
            name='sunday',
            field=models.BooleanField(default=True, help_text='Take medication on Sunday'),
        ),
        migrations.AlterField(
            model_name='medicationschedule',
            name='thursday',
            field=models.BooleanField(default=True, help_text='Take medication on Thursday'),
        ),
        migrations.AlterField(
            model_name='medicationschedule',
            name='tuesday',
            field=models.BooleanField(default=True, help_text='Take medication on Tuesday'),
        ),
        migrations.AlterField(
            model_name='medicationschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this medication schedule was last updated'),
        ),
        migrations.AlterField(
            model_name='medicationschedule',
            name='wednesday',
            field=models.BooleanField(default=True, help_text='Take medication on Wednesday'),
        ),
        migrations.AlterField(
            model_name='pharmacyintegration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this pharmacy integration was created'),
        ),
        migrations.AlterField(
            model_name='pharmacyintegration',
            name='last_sync',
            field=models.DateTimeField(blank=True, help_text='When this integration was last synchronized', null=True),
        ),
        migrations.AlterField(
            model_name='pharmacyintegration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this pharmacy integration was last updated'),
        ),
        migrations.AlterField(
            model_name='prescriptionrenewal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this prescription renewal was created'),
        ),
        migrations.AlterField(
            model_name='prescriptionrenewal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this prescription renewal was last updated'),
        ),
        migrations.AlterField(
            model_name='stockalert',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, help_text='When this alert was acknowledged', null=True),
        ),
        migrations.AlterField(
            model_name='stockalert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this stock alert was created'),
        ),
        migrations.AlterField(
            model_name='stockalert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this stock alert was last updated'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this stock transaction was created'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this stock transaction was last updated'),
        ),
        migrations.AlterField(
            model_name='stockvisualization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this stock visualization was created'),
        ),
        migrations.AlterField(
            model_name='stockvisualization',
            name='last_generated',
            field=models.DateTimeField(blank=True, help_text='When this visualization was last generated', null=True),
        ),
        migrations.AlterField(
            model_name='stockvisualization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this stock visualization was last updated'),
        ),
    ]
