# Generated by Django 5.2.4 on 2025-08-05 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0012_seed_prescription_data'),
        ('medications', '0016_final_relationships_indexes'),
    ]

    operations = [
    ]
