# Generated by Django 5.2.4 on 2025-08-05 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0018_remove_prescription_secondary_diagnoses_and_more'),
    ]

    operations = [
    ]
