# Generated by Django 5.2.4 on 2025-08-05 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0019_fix_model_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='medication',
            name='medications_pill_co_c7cfb4_idx',
        ),
        migrations.RemoveIndex(
            model_name='medication',
            name='medications_expirat_2e7409_idx',
        ),
        migrations.AlterField(
            model_name='medication',
            name='prescription_type',
            field=models.CharField(choices=[('prescription', 'Prescription Required'), ('otc', 'Over the Counter'), ('supplement', 'Supplement'), ('schedule_1', 'Schedule 1 - Highly Addictive'), ('schedule_2', 'Schedule 2 - Addictive'), ('schedule_3', 'Schedule 3 - Moderate Risk'), ('schedule_4', 'Schedule 4 - Low Risk'), ('schedule_5', 'Schedule 5 - Minimal Risk'), ('schedule_6', 'Schedule 6 - Poisonous'), ('schedule_7', 'Schedule 7 - Dangerous'), ('compounded', 'Compounded Medication'), ('generic', 'Generic Medication'), ('branded', 'Branded Medication')], default='prescription', help_text='Type of prescription required', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicationlog',
            name='schedule',
            field=models.ForeignKey(blank=True, help_text='Associated medication schedule', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medication_logs', to='medications.medicationschedule'),
        ),
    ]
