# Generated by Django 5.2.4 on 2025-08-06 07:30

from django.db import migrations


def fix_empty_image_fields(apps, schema_editor):
    """Fix empty string values in image fields by setting them to NULL."""
    Medication = apps.get_model('medications', 'Medication')
    
    # Update medications with empty string image fields to NULL
    Medication.objects.filter(medication_image='').update(medication_image=None)
    Medication.objects.filter(medication_image_thumbnail='').update(medication_image_thumbnail=None)
    Medication.objects.filter(medication_image_webp='').update(medication_image_webp=None)
    Medication.objects.filter(medication_image_avif='').update(medication_image_avif=None)
    Medication.objects.filter(medication_image_jpeg_xl='').update(medication_image_jpeg_xl=None)
    Medication.objects.filter(medication_image_original='').update(medication_image_original=None)


def reverse_fix_empty_image_fields(apps, schema_editor):
    """Reverse operation - not needed as we're just cleaning data."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0020_remove_medication_medications_pill_co_c7cfb4_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_empty_image_fields, reverse_fix_empty_image_fields),
    ]
