# Generated by Django 5.2.4 on 2025-08-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0022_enhance_streamfield_wagtail_7_0_2_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationindexpage',
            name='page_description',
            field=models.CharField(blank=True, help_text='Brief description for search engines and social media', max_length=255, verbose_name='Page Description'),
        ),
    ]
